locale                   : "vn-VN"
title                    : "Nhut-Nam Le| Gist Listing"
title_separator          : "-"
name                     : &name "Nhut-Nam Le"
description              : &description "My Github Gist Listing"
url                      : https://nhutnamhcmus.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "nhutnamhcmus/gist-listing"